### ISSUE TITLE
minishell main flow chart

### ISSUE THREAD

**Issue by JaeSeoKim** [gachi-mandoo-shell/kimchi-mandoo-shell#1]
minishell를 동작하기 위한 기본적인 flow chart에 대해서 정의필요!

**Comment by JaeSeoKim** [comment]
### 처음으로 정의 된 flow chart 추후 상세 하게 업데이트 필요!

![minishell flow chart](https://raw.githubusercontent.com/gachi-mandoo-shell/kimchi-mandoo-shell/b7ff0e91d4dde3add8c9b2ba6ffa01778fdc04c0/docs/flow_chart.drawio.svg)

**Comment by JaeSeoKim** [comment]
### BY. @jyw2671 

살려줘 재서어어

수정 가능한 노션입니다아

보고 재서가 생각하는거랑 다르면 "\n"후 `(재서)` 하고 재서 의견 적어줘여어

# 시험공부 하기싫어서 의식의 흐름대로 생각해본 minishell

### `?` (의문점들)

- "`|`" 는 어떤 역할..? (설명해주세여)

## 의식의 흐름

1. `char **envp` → `char **env`로 옮겨담기
2. `while(1)`들어가서
3. `read_cmd()` 에서 "\n"까지 read

    3-1) "\n"까지 read한 내용 double linked list에 저장(history 구현 위해)

    →  `**?**` double linked list len 저장..? 현재 위치 파악 위해..?

    - `**?**` read한 내용을 버퍼 1씩 전부 다 따로따로 저장..? 아니라면 저장 방식은..?
4. `parse_cmd()` 에서 read한 내용 parsing
5. token화 하기 (laxer가 필요한가..?)

    5-1) `is_space`와 `single quotes`, `double quotes` 기준으로 먼저 token화 한다

    이유..?

    → `echo "$PWD;"`, `echo "$PWD&&"`등 이러한 경우 해결 위해

    error case..?

    → single quotes나 double quotes가 홀수개만 있는 경우 (PS2로 넘어가게 되므로)

    5-2) "`;`" "`&&`" "`||`" 기준으로 나눈다 ⇒ **single quotes**나 **double quotes**안에 들어가 있지 않은 경우만 해당

    - 아예 `t_AST`를 나눠서 저장해준다 (`&&`인 경우는 따로 체크해준다)

    error case..?

    → quotes가 아닌 해당 토큰에 strcmp햇을시에 0이 아닌 경우 (ex. `;a`, `|||`, `1&&` 등등)

    5-3) 위의 나눠진 `t_AST`를 각각 redirection으로 나눠준다 ("`>`" "`>>`" "`<`" "`<<`")

    5-4) 그 후 명령어와 인자로 구분해 구조체에 각각 저장해준다 (`t_cmd`와 `t_arg` 구조체) 

6. parse 과정

    결과 : t_AST *cmds에 잘 저장된 t_AST들

7. exec_cmd()에서 각각의 트리 구조체들 실행해주기

# 결론 : 아무것도 하기 싫다아... 다시 시험공부하러 도망칠래....

**Comment by JaeSeoKim** [comment]
### 의식의 flow chart - jaesekim.ver

1. 기본 envp, 기타 초기화 작업 선행
2. while (1)
3. PS1 출력
4. read_cmd 실행!
5. parse_cmd 실행!
    - pipe, redirect, cmd, args, divider 등을 기준으로 token화
    - 이때 args는 각 arg로 파싱 되지 않고 `char *` 로 유지
    - token에 대한 의미 부여
    - 의미 부여 된 내용을 바탕으로 AST 완성
6. exec_cmd 실행!
    - pipe, redirect에 따른 명령어 stdin, stdout 연결 처리
    - cmd 발견시 parse_args 실행
       -  이때 `"`, `'`, `$`, `*` 등 여러가지 예외 처리
    - 받은 args를 가지고 `execve` 실행
7. 3번 으로 복귀!

**Comment by hyungraelee** [comment]
`ls` -> `/bin/ls`

`"hello wolrd" $PWD` -> [`"hello world"`, `/home/test`]
