### ISSUE TITLE
GIT REPO 관리 규칙 정의 및 문서화!

### ISSUE THREAD

**Issue by JaeSeoKim** [gachi-mandoo-shell/kimchi-mandoo-shell#12]
- [x] git commit message에 대한 규칙
- [ ] git pull request에 대한 규칙
- [ ] 기타 필요한 규칙!

**Comment by jyw2671** [comment]
git pull request에 대한 규칙
-> 함수 기능별로 자세히 pull request 하기

기타 필요한 규칙!
-> main repo에 merge시 항상 변경사항 알수 있게 두 사람 다 인지한 경우거나 아니면 꼭 pull request로 해결
  (git fetch할 경우 꼬이지 않게 하기 위해)

**Comment by JaeSeoKim** [comment]
#### git commit message는 clone 후 아래의 명령어를 통하여 템플릿 적용하여 사용할 것!

```shell
git config commit.template COMMIT_TEMPLATE
```

**Comment by jyw2671** [comment]
###  git pull request에 대한 규칙
- 각각 main repo의 feat/exec, feat/parse의 브랜치로 pull request를 날린다
- pull request는 make가 잘 될때와 norm을 통과햇을 경우에만 날린다
- 날린 pull request는 두 사람이 모두 확인 후 merge한다

**Comment by JaeSeoKim** [comment]
builtin 함수에 대한 ISSUE에 대한 경우 builtin 라벨를 생성하여 적용하는 것이 좋을 것 같습니다!
@jyw2671
