### ISSUE TITLE
cmd 별 함수 작성 계획 정리(builtin 함수)

### ISSUE THREAD

**Issue by jyw2671** [gachi-mandoo-shell/kimchi-mandoo-shell#23]
- [ ]  `echo` with option ’`-n`’
- [ ]  `cd` with only a relative or absolute path
- [ ]  `pwd` without any options
- [ ]  `export` without any options
- [ ]  `unset` without any options
- [ ]  `env` without any options and any arguments
- [ ]  `exit` without any options

**Comment by jyw2671** [comment]
### **pwd**

`unistd.h`에 있는 `getcwd()`함수를 사용하여 `pwd` 명령어와 같은 동작을 하는 `ft_pwd` 함수 생성

- `char *getcwd(char *buf, size_t size);` `buf`에 현재 위치의 절대 경로 값을 넣고 그 주소값을 리턴하는 함수

    → 실패시 NULL 리턴하므로 리턴값으로 잘 받아왔는지 체크

    → pwd 명령어..? → PATH_MAX+1 (or PATH_MAX..?) 만큼의 공간을 할당하고 getcwd 로 path를 받아온다 → 그리고 리턴값 체크로 잘 받아왔는지 확인

- 구현한 `ft_pwd(void)` 함수를 `exec_cmd(t_AST *cmds, char **envp);` 함수에서 알맞은 위치에서 호출
- 경로의 최대길이인 `MAX_PATH_LEN` 상수 매크로 선언

    ⇒ PATH_MAX

    PATH_MAX는 패스 이름이 가질 수 있는 최대 글자 수를 나타냅니다. 패스 이름이란 디렉토리 이름을 포함한 파일 이름을 뜻합니다. (예: "/usr/bin/ls", "/opt/share/info"). 문자열의 끝을 나타내는 '\0'도 포함입니다. 따라서 정확히 파일이 가질 수 있는 글자 수의 총 길이는 PATH_MAX - 1이 됩니다.

**Comment by jyw2671** [comment]
### **cd**

`unistd.h`에 있는 `chdir()`함수를 사용하여 `cd` 명령어와 같은 동작을 하는 `ft_cd` 함수 생성

- `int chdir(const char *path);` `path`에 이동할 상대/절대 경로값을 넣고 실행했을 때, 이상이 없다면 현재 working directory를 이동 (반환값 : 정상작동시 0, 에러시 -1)

**Comment by JaeSeoKim** [comment]
builtin 함수별 이슈로 변경 하였으므로 이 이슈는 CLOSE 처리 하겠습니다~!
