### ISSUE TITLE
redirect 처리에 대한 아이디어!

### ISSUE THREAD

**Issue by JaeSeoKim** [gachi-mandoo-shell/kimchi-mandoo-shell#26]
# redirect의 작동 원리

> cmd 중간의 어느 위치에 있어도 작동을 함

### ex1

```shell
> file echo helloworld
```
result
```
// file
helloworld
```

### ex2

```shell
echo > file  helloworld 
```
result
```
// file
helloworld
```

### ex3

```shell
echo hello > file  world 
```
result
```
// file
hello world
```

### ex3

```shell
> file2 echo hello > file  world 
```
result
file2는 파일이 없을 시 생성을 하고 file이 마지막으로 정의된 redirect 지점이니 file에다가 write
```
// file2
// file
hello world
```

_Originally posted by @JaeSeoKim in https://github.com/gachi-mandoo-shell/kimchi-mandoo-shell/issues/24#issuecomment-820935719_

**Comment by jyw2671** [comment]
token에서 strcmp를 하여 redirection을 만날시 그 다음 공백까지 덩어리로 토큰을 만든다
```shell
ls>a
ls >a
ls > a
```
위의 케이스 모두 정상 작동하므로
