### ISSUE TITLE
확인 요청! (normalize 함수 수정 이후 인자가 있는 명령이 동작을 안함)

### ISSUE THREAD

**Issue by jyw2671** [gachi-mandoo-shell/kimchi-mandoo-shell#65]
`ls` 같은 명령은 동작을 하지만 `ls -al`이나 `cat file`같이 인자가 있는 명령들이 동작을 안합니다!

**Comment by JaeSeoKim** [comment]
![image](https://user-images.githubusercontent.com/48559454/118098885-737ccd00-b40f-11eb-8eff-55b9856e09dd.png)

함수에 대해서 잘 못 사용하고 있었습니다!

**Comment by jyw2671** [comment]
확인하였습니다!
