### ISSUE TITLE
Custom_error message 정의

### ISSUE THREAD

**Issue by jyw2671** [gachi-mandoo-shell/kimchi-mandoo-shell#9]
Custom_error message 정의

**Comment by jyw2671** [comment]
### char ***strerror**(int errnum);
    - #include <string.h>
    - errnum을 설명하는 에러 메세지를 반환해준다.
### errno
    - #include <errno.h>
    - 자동으로 발생된 에러에 대한 번호가 저장됨

**Comment by JaeSeoKim** [comment]
`"ERROR: Memory allocation failure\n"`

**Comment by JaeSeoKim** [comment]
@jyw2671 

기존 parsing 단계에서 error시에는 반환값을 Define시킨 값을 return 시키고 있는데 이 부분을 전역 변수를 통하여 errorr 상태를 저장 하도록 수정 하는 것이 어떨까요?

`parse_arg` 함수를 제작 하는 도중 에러 상태에 대해서 추가를 해야 하는 일이 생겼는데 과연 에러케이스가 여러개 생겨진다면 반환 되는 값이 NULL이 아닌 특정 값을 반환 하지만 0이 아닌 값은 실제 메모리 주소로 참조가 가능하기 때문에 0이 아닌 값을 반환 하는 것이 맞는 부분인지 의문이 드네요.

### 예시
`parsing_*` 시리즈 함수 작동 실패시 NULL 반환.
이 때 전역 변수에 있는 예(g_sh.parse_error)의 값을 확인 하여 해당하는 에러 확인
